new "manual" import method for VPN configs in Viscosity, so viscosity no longer gives an annoying popup

diff --git a/xsvpn b/xsvpn
--- a/xsvpn
+++ b/xsvpn
@@ -150,6 +150,123 @@ scan_configured_vpn_connections() {
     : ${old_conn_name:="$expired_conn_name"}
 }
 
+# try to import a new connection profile
+import_new_connection() {
+    infile="$1"
+
+    # determine the name of the connection
+    name="${infile##*/}"
+    ext="${name##*.}"
+    name="${name%.$ext}"
+
+    # determine a directory for the config to be stored
+    n=1
+    while [ -e "$CONN_DIR/$n" ]
+    do
+        n=$(( $n + 1 ))
+        if [ $n -gt 100 ]; then
+            echo Too many existing VPN connections 1>&2
+            return 1
+        fi
+    done
+    CONFDIR="$CONN_DIR/$n"
+    if ! mkdir -m 0755 "$CONFDIR"; then
+        printf "%s\n" "Cannot create $CONFDIR" 1>&2
+        return 1
+    fi
+    confhead="#-- Configuration Generated By Viscosity --#$LF$LF"
+    confhead="${confhead}#viscosity name $name$LF"
+    confhead="${confhead}#viscosity protocol openvpn$LF"
+    confremote=""
+    conftail=""
+    wrfile=""
+    is_client="false"
+    # for stripping \r off of downloaded file, if any
+    CR=$( printf "\r" )
+    while read confln
+    do
+        confln="${confln%$CR}"
+        if [ -n "$wrfile" ]; then
+            if [ "$confln" == "$endtag" ]; then
+                wrfile=""
+            else
+                printf "%s\n" "$confln" >> "$wrfile"
+            fi
+        else
+            case "$confln" in
+                "# OpenVPN"*)
+                    ;;
+                dev*|nobind*|remote-*|server-*|tls-*|ncp-*|cipher*|auth*|route*)
+                    conftail="${conftail}${confln}$LF"
+                    ;;
+                client)
+                    conftail="${conftail}tls-client ${LF}pull $LF"
+                    is_client="true"
+                    ;;
+                "verb "*)
+                    # verbosity setting, ignored.
+                    ;;
+                "remote "*)
+                    if [ -n "$confremote" ]; then
+                        printf "%s\n" "Too many remote lines in conf: $confln" 1>&2
+                        rm -f "$CONFDIR"/*
+                        rmdir "$CONFDIR"
+                        return 1
+                    fi
+                    confremote="$confln"
+                    ;;
+                "#viscosity "*)
+                    confhead="${confhead}$confln$LF"
+                    ;;
+                "<ca>")
+                    conftail="${conftail}ca ca.crt$LF"
+                    wrfile="$CONFDIR/ca.crt"
+                    endtag="</ca>"
+                    ;;
+                "<cert>")
+                    conftail="${conftail}cert cert.crt$LF"
+                    wrfile="$CONFDIR/cert.crt"
+                    endtag="</cert>"
+                    ;;
+                "<key>")
+                    conftail="${conftail}key key.key$LF"
+                    wrfile="$CONFDIR/key.key"
+                    endtag="</key>"
+                    ;;
+                "<tls-crypt>")
+                    conftail="${conftail}tls-crypt tlscrypt.key$LF"
+                    wrfile="$CONFDIR/tlscrypt.key"
+                    endtag="</tls-crypt>"
+                    ;;
+                *)
+                    printf "%s\n" "Unknown line in downloaded config: $confln" 1>&2
+                    rm -f "$CONFDIR"/*
+                    rmdir "$CONFDIR"
+                    return 1
+                    ;;
+            esac
+        fi
+    done < "$infile"
+    if [ -n "$wrfile" ]; then
+        printf "%s\n" "Unexpected EOF reading $infile, writing $wrfile" 1>&2
+        rm -r "$CONFDIR"/*
+        rmdir "$CONFDIR"
+        return 1
+    fi
+    case "$confremote" in
+        *tcp)
+            if $is_client; then
+                confremote="${confremote}-client"
+            else
+                confremote="${confremote}-server"
+            fi
+            ;;
+    esac
+    printf "%s%s\n%s" "$confhead" "$confremote" "$conftail" > "$CONFDIR/config.conf"
+    printf "%s\n" "Imported new config in $infile to $CONFDIR"
+    return 0
+}
+
 download_new_profile() {
     # fetch new VPN config
 
@@ -436,23 +553,35 @@ if download_new_profile; then
     fi
     if [ ! -s $conn_list -a ${#expired_conn[@]} -gt 0 ]; then
         delete_expired_connections "${expired_conn[@]}"
+    else
+        echo Stopping viscosity to import new connection
+        osascript -e 'tell application "Viscosity" to quit'
     fi
     # add new profile to connections
     echo Importing new connection...
-    open -a "$APP" "$new_vpn_profile"
-    # wait some time until viscosity imported it
-    max_wait=30
-    while true; do
-        sleep 1
-        max_wait=$(( $max_wait - 1 ))
-        # rescan connections
+    if import_new_connection "$new_vpn_profile"; then
+        open -a "$APP"
+        # rescan connections to set conn_name
         scan_configured_vpn_connections
-        if [ -n "$conn_name" ]; then
-            break
-        elif [ $max_wait -le 0 ]; then
-            error "Error waiting for viscosity to import connection. Stop."
+        if [ -z "$conn_name" ]; then
+            error "VPN profile import failed? Stop."
         fi
-    done
+    else
+        open -a "$APP" "$new_vpn_profile"
+        # wait some time until viscosity imported it
+        max_wait=30
+        while true; do
+            sleep 1
+            max_wait=$(( $max_wait - 1 ))
+            # rescan connections
+            scan_configured_vpn_connections
+            if [ -n "$conn_name" ]; then
+                break
+            elif [ $max_wait -le 0 ]; then
+                error "Error waiting for viscosity to import connection. Stop."
+            fi
+        done
+    fi
 elif [ -n "$old_conn" ]; then
     printf "%s\n" "Download failed, using older connection $old_conn_name"
     conn_name="$old_conn_name"
